### ISSUE TITLE
Paste into editor

### ISSUE THREAD

**Issue by syntax53** [mike-douglas/tsm-editor#74]
Hello.  Neat site for TSM strings... except whenever I paste anything into the string with Control+V, it wipes out the string and only puts in my paste.  Sometimes I'm pasting pieces from another window or from in-game.  What makes it worse, is there is no undo after it happens (control+Z doesn't work) and you lose everything.

So, the feature request is... don't clear the box when pasting :)

**Comment by mike-douglas** [comment]
Hi there! Thanks for the feature request, I was able to fix that for you.
